-- Enable foreign key constraints in SQLite
PRAGMA foreign_keys = ON;


-- STUDENT TABLE
CREATE TABLE IF NOT EXISTS student (
    NID INTEGER PRIMARY KEY NOT NULL,
    F_NAME VARCHAR(50) NOT NULL,
    L_NAME VARCHAR(40) NOT NULL,
    B_DATE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    EMAIL_ADDRESS VARCHAR(100) UNIQUE NOT NULL
);


-- SUBJECTS TABLE
CREATE TABLE IF NOT EXISTS SUBJECTS (
    SUBJECT_CODE INTEGER PRIMARY KEY NOT NULL,
    SUBJECT_UNIT INTEGER NOT NULL,
    SUBJECT_UCFS INTEGER NOT NULL
);


-- LECTURER TABLE
CREATE TABLE IF NOT EXISTS LECTURER (
    L_ID INTEGER PRIMARY KEY NOT NULL,
    L_LASTNAME VARCHAR(50) NOT NULL,
    L_FIRSTNAME VARCHAR(50) NOT NULL,
    L_EMAIL VARCHAR(100) NOT NULL,
    L_ADDRESS VARCHAR(50) NOT NULL
);


-- ENROLLMENT TABLE
CREATE TABLE IF NOT EXISTS ENROLLMENT (
    STUDENT_NUM INTEGER NOT NULL,
    DATE_OF_ENROLLMENT VARCHAR(20) NOT NULL,
    SUBJECT_CODE INTEGER NOT NULL,
    CGPA FLOAT NOT NULL,

    FOREIGN KEY (STUDENT_NUM)
        REFERENCES student(NID)
        ON DELETE CASCADE,

    FOREIGN KEY (SUBJECT_CODE)
        REFERENCES SUBJECTS(SUBJECT_CODE)
        ON DELETE CASCADE
);


-- LECTURE TABLE
CREATE TABLE IF NOT EXISTS Lecture (
    CCA INTEGER PRIMARY KEY,
    Lecture_name TEXT NOT NULL,
    Lecturer_ID INTEGER NOT NULL,
    Subject_Code INTEGER NOT NULL,
    Date TEXT,
    Time TEXT,

    FOREIGN KEY (Lecturer_ID)
        REFERENCES LECTURER(L_ID)
        ON DELETE CASCADE,

    FOREIGN KEY (Subject_Code)
        REFERENCES SUBJECTS(SUBJECT_CODE)
        ON DELETE CASCADE
);